services:
  postgres:
    image: postgres:16-alpine
    container_name: taxi-postgres
    environment:
      POSTGRES_DB: ${PG_DB}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASS}
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 3s
      retries: 20

  redis:
    image: redis:7-alpine
    container_name: taxi-redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 20

  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: taxi-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    # ports:
    # - "5672:5672"
    # - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 3s
      retries: 20

  user-service:
    build: ./user-service
    container_name: taxi-user-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${PG_DB}
      SPRING_DATASOURCE_USERNAME: ${PG_USER}
      SPRING_DATASOURCE_PASSWORD: ${PG_PASS}
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      JWT_SECRET: ${JWT}
    ports:
      - "8081:8081"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  trip-service:
    build: ./trip-service
    container_name: taxi-trip-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${PG_DB}
      SPRING_DATASOURCE_USERNAME: ${PG_USER}
      SPRING_DATASOURCE_PASSWORD: ${PG_PASS}
      USER_SERVICE_URL: http://user-service:8081
      NOTIFICATION_SERVICE_URL: http://notification-service:8083
      JWT_SECRET: ${JWT}
    ports:
      - "8082:8082"
    depends_on:
      postgres:
        condition: service_healthy
      user-service:
        condition: service_started
      notification-service:
        condition: service_started

  notification-service:
    build: ./notification-service
    container_name: taxi-notification-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${PG_DB}
      SPRING_DATASOURCE_USERNAME: ${PG_USER}
      SPRING_DATASOURCE_PASSWORD: ${PG_PASS}
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: ${RABBITMQ_USER:-guest}
      SPRING_RABBITMQ_PASSWORD: ${RABBITMQ_PASS:-guest}
      NOTIFICATION_SEND_DELAY_MS: ${NOTIFICATION_SEND_DELAY_MS:-1000}
      JWT_SECRET: ${JWT}
    ports:
      - "8083:8083"
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
