/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.3.0/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation(libs.junit.jupiter)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // Mockito Core
    testImplementation("org.mockito:mockito-core:5.14.2")

    // Mockito Extension for JUnit 5 (enables @Mock, @InjectMocks automatically)
    testImplementation("org.mockito:mockito-junit-jupiter:5.14.2")

    // This dependency is used by the application.
    implementation(libs.guava)
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

application {
    // Define the main class for the application.
    mainClass = "org.Main"
}

tasks.named<JavaExec>("run") {
    standardInput = System.`in`
    systemProperties["java.util.logging.ConsoleHandler.level"] = "INFO"
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()

    jvmArgs("-Dnet.bytebuddy.experimental=true")
}
